swagger: "2.0"
info:
  description: The Jobber service handles web requests for job reporting functionality
  title: Jobber
  version: 1.0.0
consumes:
- application/json
- text/plain
produces:
- application/json
- text/plain
schemes:
- http
  #- https
paths:
  /v1/jobs:
    get:
      tags: ["jobs"]
      operationId: getJobs
      parameters:
      - name: "numLatest"
        description: "Determines the number of the most-recenly created jobs to query"
        required: false
        in: query
        type: integer
      responses:
        '200':
          description: "list of jobs"
          schema:
            type: array
            items:
              $ref: "#/definitions/Job"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
    post:
      tags: ["job"]
      operationId: createJob
      consumes:
      - application/json
      parameters:
      - name: "jobSpec"
        description: "Creates a new job with the specified job spec"
        required: true
        in: body
        schema:
          $ref: "#/definitions/JobSpec"
      responses:
        '202':
          description: Accepted
          schema:
            $ref: "#/definitions/ID"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /v1/jobs/{id}:
    parameters:
          - $ref: "#/parameters/IDParam"
    get:
     tags: ["job"]
     description: "Retrieves a job by ID"
     operationId: getJob
     responses:
       '200':
         description: OK
         schema:
           $ref: "#/definitions/Job"
       default:
         description: error
         schema:
           $ref: "#/definitions/Error"
    patch:
      tags: ["job"]
      operationId: updateJob
      consumes:
      - application/json
      parameters:
      - name: "status"
        description: "Updates an existing service instance"
        required: false
        in: body
        schema:
          $ref: "#/definitions/JobStatus"
      responses:
        '202':
          description: Accepted
        default:
          description: error
          schema:
            $ref: "#/definitions/Error"
    delete:
     tags: ["job"]
     description: "Deletes a job specified by ID"
     operationId: deleteJob
     responses:
       '200':
         description: OK
       default:
         description: error
         schema:
           $ref: "#/definitions/Error"
definitions:
  Job:
    type: object
    required:
    - id
    - owner
    - created_at
    - updated_at
    - type
    - status
    properties:
      id:
        $ref: "#/definitions/ID"
      owner:
        type: string
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
      completed_at:
        type: string
        format: date-time
      type:
        type: string
      status:
        $ref: "#/definitions/JobStatus"
      tags:
        type: array
        items:
          $ref: "#/definitions/Tag"
          description: Allows jobs to be tagged with user-defined strings for customizable search.
  JobStatus:
    type: string
    enum:
    - created
    - running
    - succeeded
    - failed
    - unknown
  JobSpec:
    type: object
    required:
    - type
    properties:
      type:
        type: string
      tags:
        type: array
        items:
          $ref: "#/definitions/Tag"
          description: Allows jobs to be tagged with user-defined strings for customizable search.
  ID:
    type: string
    readOnly: true
    minLength: 1
  Tag:
    type: string
    readOnly: false
    minLength: 1
  Error:
    type: object
    required:
    - code
    - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
parameters:
  IDParam:
    name: id
    type: string
    in: path
    required: true
